### ISSUE TITLE
Remove deprecated file

### ISSUE THREAD

**Issue by pkrog** [Modelbirdman/python-ap#15]
https://github.com/Modelbirdman/python-ap/blob/249d62e5af329dd0d3c2dffbf36f8df6f952db15/pythonsnake/snake#L1-L15

Try to keep your repository clean. Remove this deprecated file.

**Comment by Modelbirdman** [comment]
comment puis-je supprimer ce fichier sur github?

**Comment by pkrog** [comment]
Dans le terminal tu utilises `git rm pythonsnake/snake`, puis `git commit -v`.
